#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER fleet WITH PASSWORD '$FLEET_DATABASE_PASSWORD';
    CREATE USER airflow WITH PASSWORD '$AIRFLOW_DATABASE_PASSWORD';
    CREATE USER grafana WITH PASSWORD '$GRAFANA_DATABASE_PASSWORD';
    CREATE USER superset WITH PASSWORD '$SUPERSET_DATABASE_PASSWORD';
    CREATE USER reader WITH PASSWORD '$READER_DATABASE_PASSWORD';

    CREATE DATABASE fleet;
    CREATE DATABASE airflow;
    CREATE DATABASE grafana;
    CREATE DATABASE superset;

    GRANT ALL PRIVILEGES ON DATABASE fleet TO fleet;
    GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
    GRANT ALL PRIVILEGES ON DATABASE grafana TO grafana;
    GRANT ALL PRIVILEGES ON DATABASE superset TO superset;

    \c fleet
    GRANT ALL PRIVILEGES ON SCHEMA public TO fleet;
    SET ROLE fleet;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO reader;
    \c airflow
    GRANT ALL PRIVILEGES ON SCHEMA public TO airflow;
    \c grafana
    GRANT ALL PRIVILEGES ON SCHEMA public TO grafana;
    \c superset
    GRANT ALL PRIVILEGES ON SCHEMA public TO superset;
EOSQL
