slice_name: Active aircraft
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 4__table
  viz_type: echarts_timeseries_line
  x_axis: time
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SQL
    sqlExpression: count(*)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: false
    label: count(*)
    optionName: metric_ily5kuojaf_r5wm3enavki
  - expressionType: SQL
    sqlExpression: countIf(not on_ground)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: false
    label: countIf(not on_ground)
    optionName: metric_hvyv9nu1mr_3xyivlwiqta
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: time
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":4,"type":"table"},"force":false,"queries":[{"filters":[{"col":"time","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"time","label":"time","expressionType":"SQL"}],"metrics":[{"expressionType":"SQL","sqlExpression":"count(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"count(*)","optionName":"metric_ily5kuojaf_r5wm3enavki"},{"expressionType":"SQL","sqlExpression":"countIf(not
  on_ground)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"countIf(not
  on_ground)","optionName":"metric_hvyv9nu1mr_3xyivlwiqta"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"count(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"count(*)","optionName":"metric_ily5kuojaf_r5wm3enavki"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["time"],"columns":[],"aggregates":{"count(*)":{"operator":"mean"},"countIf(not
  on_ground)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"4__table","viz_type":"echarts_timeseries_line","x_axis":"time","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SQL","sqlExpression":"count(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"count(*)","optionName":"metric_ily5kuojaf_r5wm3enavki"},{"expressionType":"SQL","sqlExpression":"countIf(not
  on_ground)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"countIf(not
  on_ground)","optionName":"metric_hvyv9nu1mr_3xyivlwiqta"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","subject":"time","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","only_total":true,"opacity":0.2,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: eb7662f4-16f9-4b4a-b6ff-70bb7a0a19e9
version: 1.0.0
dataset_uuid: 9fb9276b-30db-437d-b213-75047700c47a
