slice_name: Flight endpoints
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 3__table
  viz_type: echarts_timeseries_line
  slice_id: 5
  x_axis: time_position
  metrics:
  - count
  groupby:
  - datasourceWarning: false
    expressionType: SQL
    label: on_ground
    sqlExpression: case when on_ground then 'Landings' else 'Takeoffs' end
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_qaqgyj9sez_g1gebxnmgjd
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: time_position
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_yodz4qk720s_zll48ptx3h
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: on_ground != prev_on_ground
    subject: null
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource": {"id": 3, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "time_position", "op": "TEMPORAL_RANGE", "val": "No filter"}],
  "extras": {"having": "", "where": "(on_ground != prev_on_ground)"}, "applied_time_extras":
  {}, "columns": [{"columnType": "BASE_AXIS", "sqlExpression": "time_position", "label":
  "time_position", "expressionType": "SQL"}, {"datasourceWarning": false, "expressionType":
  "SQL", "label": "on_ground", "sqlExpression": "case when on_ground then ''Landings''
  else ''Takeoffs'' end"}], "metrics": ["count"], "orderby": [["count", false]], "annotation_layers":
  [], "row_limit": 10000, "series_columns": [{"datasourceWarning": false, "expressionType":
  "SQL", "label": "on_ground", "sqlExpression": "case when on_ground then ''Landings''
  else ''Takeoffs'' end"}], "series_limit": 0, "order_desc": true, "url_params": {},
  "custom_params": {}, "custom_form_data": {}, "time_offsets": [], "post_processing":
  [{"operation": "pivot", "options": {"index": ["time_position"], "columns": ["on_ground"],
  "aggregates": {"count": {"operator": "mean"}}, "drop_missing_columns": false}},
  {"operation": "rename", "options": {"columns": {"count": null}, "level": 0, "inplace":
  true}}, {"operation": "flatten"}]}], "form_data": {"datasource": "3__table", "viz_type":
  "echarts_timeseries_line", "slice_id": 5, "x_axis": "time_position", "metrics":
  ["count"], "groupby": [{"datasourceWarning": false, "expressionType": "SQL", "label":
  "on_ground", "sqlExpression": "case when on_ground then ''Landings'' else ''Takeoffs''
  end"}], "adhoc_filters": [{"clause": "WHERE", "comparator": "No filter", "datasourceWarning":
  false, "expressionType": "SIMPLE", "filterOptionName": "filter_qaqgyj9sez_g1gebxnmgjd",
  "isExtra": false, "isNew": false, "operator": "TEMPORAL_RANGE", "sqlExpression":
  null, "subject": "time_position"}, {"clause": "WHERE", "comparator": null, "datasourceWarning":
  false, "expressionType": "SQL", "filterOptionName": "filter_yodz4qk720s_zll48ptx3h",
  "isExtra": false, "isNew": false, "operator": null, "sqlExpression": "on_ground
  != prev_on_ground", "subject": null}], "row_limit": 10000, "truncate_metric": true,
  "show_empty_columns": true, "comparison_type": "values", "annotation_layers": [],
  "forecastPeriods": 10, "forecastInterval": 0.8, "x_axis_title_margin": 15, "y_axis_title_margin":
  15, "y_axis_title_position": "Left", "sort_series_type": "sum", "color_scheme":
  "supersetColors", "seriesType": "line", "only_total": true, "opacity": 0.2, "markerSize":
  6, "show_legend": true, "legendType": "scroll", "legendOrientation": "top", "x_axis_time_format":
  "smart_date", "rich_tooltip": true, "showTooltipTotal": true, "showTooltipPercentage":
  true, "tooltipTimeFormat": "smart_date", "y_axis_format": "SMART_NUMBER", "truncateXAxis":
  true, "y_axis_bounds": [null, null], "extra_form_data": {}, "dashboards": [1], "force":
  false, "result_format": "json", "result_type": "full"}, "result_format": "json",
  "result_type": "full"}'
cache_timeout: null
uuid: 64f20c22-1fe3-453a-819c-f54099dff742
version: 1.0.0
dataset_uuid: e0eb5f6f-1667-4f72-b512-50e3ffcfefd4
