import os


POSTGRES_CONN_ID = 'postgres'
CLICKHOUSE_CONN_ID = 'clickhouse'
SPARK_CONN_ID = 'spark'

POSTGRES_DEFAULT_PORT = 5432
CLICKHOUSE_DEFAULT_PORT = 9000
CLICKHOUSE_DEFAULT_HTTP_PORT = 8123
SPARK_DEFAULT_PORT = 7077

SPARK_POSTGRES_PACKAGES = os.environ['POSTGRES_JDBC_DRIVER']
SPARK_CLICKHOUSE_PACKAGES = os.environ['SPARK_CLICKHOUSE_CONNECTOR']
