#!/bin/sh
set -e

GMT_VERSION=6
GMT_LIBRARY_NAME=libgmt.so
GMT_LIBRARY_PATH=$(dirname "$(find / -name $GMT_LIBRARY_NAME.$GMT_VERSION)")

ln -s $GMT_LIBRARY_NAME.$GMT_VERSION "$GMT_LIBRARY_PATH"/$GMT_LIBRARY_NAME
